---

- name: "instaling website"
  hosts: all
  become: true
  vars_files:
    - variables.vars
  
  tasks:
    - include_tasks: task.yml
      when: ansible_distribution == "Amazon" and ansible_mounts[0].size_available >= 50000000

#alert if there is no min space in disk
    - include_tasks: task-2.yml
      when: ansible_distribution == "Amazon" and ansible_mounts[0].size_available <= 50000000
      
    
